packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  onnxruntime-node: true
  prisma: true
  protobufjs: true

onlyBuiltDependencies:
  - electron
  - esbuild
  - electron-winstaller
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - better-sqlite3

overrides:
  'minio>query-string': 9.5.1
  'minio>stream-json': 3.7.0

patchedDependencies:
  app-builder-lib@26.15.3: patches/app-builder-lib@26.15.3.patch
  minio@8.0.7: patches/minio@8.0.7.patch
