FROM node:22-bookworm-slim AS build
RUN corepack enable
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @tescord/types build && pnpm --filter @tescord/web build

FROM nginx:1.27.2-alpine
COPY --from=build /app/apps/web/dist /usr/share/nginx/html
