FROM node:22-bookworm-slim AS build
RUN corepack enable
WORKDIR /app
COPY . .
ENV DATABASE_PROVIDER=postgresql
ENV DATABASE_URL=postgresql://build:build@localhost:5432/tescord
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @tescord/types build && pnpm --filter @tescord/server build

FROM node:22-bookworm-slim
RUN corepack enable
WORKDIR /app
COPY --from=build /app /app
ENV NODE_ENV=production
ENV DATABASE_PROVIDER=postgresql
CMD ["pnpm", "--filter", "@tescord/server", "start"]
