FROM docker.io/library/node:22-bookworm-slim AS build
RUN apt-get update && apt-get install -y --no-install-recommends openssl && rm -rf /var/lib/apt/lists/*
RUN corepack enable
WORKDIR /app
COPY . .
ENV DATABASE_PROVIDER=postgresql
ENV DATABASE_URL=postgresql://build:build@localhost:5432/tescord
RUN pnpm --filter @tescord/server... install --frozen-lockfile
RUN pnpm --filter @tescord/types build && pnpm --filter @tescord/server build

FROM docker.io/library/node:22-bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends openssl && rm -rf /var/lib/apt/lists/*
RUN corepack enable
WORKDIR /app
COPY --from=build /app /app
ENV NODE_ENV=production
ENV DATABASE_PROVIDER=postgresql
CMD ["pnpm", "--filter", "@tescord/server", "start"]
