FROM docker.io/library/node:22-bookworm-slim AS build
RUN corepack enable
WORKDIR /app
COPY . .
RUN pnpm --filter @tescord/web... --filter @tescord/server... install --frozen-lockfile
RUN pnpm --filter @tescord/types build && pnpm --filter @tescord/web build

FROM docker.io/library/nginx:1.27.2-alpine
COPY --from=build /app/apps/web/dist /usr/share/nginx/html
