export interface EmojiItem {
  emoji: string;
  name: string;
  category:
    | "people"
    | "nature"
    | "food"
    | "activities"
    | "travel"
    | "objects"
    | "symbols"
    | "flags";
  keywords: string[];
}

export const EMOJI_CATEGORIES = [
  { id: "recent", labelKey: "chat:emojiCategoryRecent", icon: "Clock" },
  { id: "server", labelKey: "chat:emojiCategoryServer", icon: "Server" },
  { id: "user", labelKey: "chat:emojiCategoryUser", icon: "User" },
  { id: "people", labelKey: "chat:emojiCategoryPeople", icon: "Smile" },
  { id: "nature", labelKey: "chat:emojiCategoryNature", icon: "Trees" },
  { id: "food", labelKey: "chat:emojiCategoryFood", icon: "Utensils" },
  {
    id: "activities",
    labelKey: "chat:emojiCategoryActivities",
    icon: "Gamepad2",
  },
  { id: "travel", labelKey: "chat:emojiCategoryTravel", icon: "Plane" },
  { id: "objects", labelKey: "chat:emojiCategoryObjects", icon: "Lightbulb" },
  { id: "symbols", labelKey: "chat:emojiCategorySymbols", icon: "Hash" },
  { id: "flags", labelKey: "chat:emojiCategoryFlags", icon: "Flag" },
] as const;

export const UNICODE_EMOJIS: EmojiItem[] = [
  // People & Smileys
  {
    emoji: "😀",
    name: "grinning",
    category: "people",
    keywords: ["smile", "happy", "笑", "高兴"],
  },
  {
    emoji: "😃",
    name: "smiley",
    category: "people",
    keywords: ["smile", "happy", "大笑"],
  },
  {
    emoji: "😄",
    name: "smile",
    category: "people",
    keywords: ["happy", "laugh", "微笑"],
  },
  {
    emoji: "😁",
    name: "grin",
    category: "people",
    keywords: ["teeth", "嬉笑", "露齿笑"],
  },
  {
    emoji: "😆",
    name: "laughing",
    category: "people",
    keywords: ["happy", "haha", "哈哈", "狂笑"],
  },
  {
    emoji: "😅",
    name: "sweat_smile",
    category: "people",
    keywords: ["hot", "sweat", "苦笑", "尴尬"],
  },
  {
    emoji: "🤣",
    name: "rofl",
    category: "people",
    keywords: ["floor", "laugh", "笑死", "笑翻"],
  },
  {
    emoji: "😂",
    name: "joy",
    category: "people",
    keywords: ["cry", "laugh", "笑哭", "眼泪"],
  },
  {
    emoji: "🙂",
    name: "slight_smile",
    category: "people",
    keywords: ["smile", "微笑", "呵呵"],
  },
  {
    emoji: "🙃",
    name: "upside_down",
    category: "people",
    keywords: ["silly", "倒脸", "阴阳"],
  },
  {
    emoji: "😉",
    name: "wink",
    category: "people",
    keywords: ["flirt", "眨眼"],
  },
  {
    emoji: "😊",
    name: "blush",
    category: "people",
    keywords: ["cute", "shy", "害羞", "脸红"],
  },
  {
    emoji: "😇",
    name: "innocent",
    category: "people",
    keywords: ["angel", "天使", "善良"],
  },
  {
    emoji: "🥰",
    name: "smiling_face_with_three_hearts",
    category: "people",
    keywords: ["love", "三颗心", "幸福"],
  },
  {
    emoji: "😍",
    name: "heart_eyes",
    category: "people",
    keywords: ["love", "色", "爱慕"],
  },
  {
    emoji: "🤩",
    name: "star_struck",
    category: "people",
    keywords: ["star", "eyes", "崇拜", "星星眼"],
  },
  {
    emoji: "😘",
    name: "kissing_heart",
    category: "people",
    keywords: ["kiss", "love", "飞吻", "亲亲"],
  },
  {
    emoji: "😋",
    name: "yum",
    category: "people",
    keywords: ["tasty", "delicious", "好吃", "吐舌"],
  },
  {
    emoji: "😜",
    name: "stuck_out_tongue_winking_eye",
    category: "people",
    keywords: ["silly", "调皮", "眨眼吐舌"],
  },
  {
    emoji: "🤪",
    name: "zany_face",
    category: "people",
    keywords: ["crazy", "滑稽", "古怪"],
  },
  {
    emoji: "😝",
    name: "stuck_out_tongue_closed_eyes",
    category: "people",
    keywords: ["prank", "吐舌鬼脸"],
  },
  {
    emoji: "🤑",
    name: "money_mouth_face",
    category: "people",
    keywords: ["rich", "money", "发财", "发光"],
  },
  { emoji: "🤗", name: "hugs", category: "people", keywords: ["hug", "拥抱"] },
  {
    emoji: "🤭",
    name: "hand_over_mouth",
    category: "people",
    keywords: ["quiet", "偷笑"],
  },
  {
    emoji: "🤫",
    name: "shushing_face",
    category: "people",
    keywords: ["quiet", "shh", "嘘", "安静"],
  },
  {
    emoji: "🤔",
    name: "thinking",
    category: "people",
    keywords: ["think", "hmm", "思考", "沉思"],
  },
  {
    emoji: "🤐",
    name: "zipper_mouth",
    category: "people",
    keywords: ["silent", "闭嘴", "保密"],
  },
  {
    emoji: "🤨",
    name: "raised_eyebrow",
    category: "people",
    keywords: ["doubt", "挑眉", "怀疑"],
  },
  {
    emoji: "😐",
    name: "neutral_face",
    category: "people",
    keywords: ["meh", "平淡", "面无表情"],
  },
  {
    emoji: "😑",
    name: "expressionless",
    category: "people",
    keywords: ["blank", "无语"],
  },
  {
    emoji: "😶",
    name: "no_mouth",
    category: "people",
    keywords: ["silent", "没有嘴"],
  },
  {
    emoji: "😏",
    name: "smirk",
    category: "people",
    keywords: ["flirt", "邪魅", "坏笑"],
  },
  {
    emoji: "😒",
    name: "unamused",
    category: "people",
    keywords: ["bored", "不悦", "鄙视"],
  },
  {
    emoji: "🙄",
    name: "roll_eyes",
    category: "people",
    keywords: ["eyeroll", "翻白眼"],
  },
  {
    emoji: "😬",
    name: "grimacing",
    category: "people",
    keywords: ["awkward", "龇牙", "尴尬"],
  },
  {
    emoji: "🤥",
    name: "lying_face",
    category: "people",
    keywords: ["liar", "匹诺曹", "说谎"],
  },
  {
    emoji: "😌",
    name: "relieved",
    category: "people",
    keywords: ["peace", "安心", "宽慰"],
  },
  {
    emoji: "😔",
    name: "pensive",
    category: "people",
    keywords: ["sad", "难受", "失落"],
  },
  {
    emoji: "😪",
    name: "sleepy",
    category: "people",
    keywords: ["tired", "困", "瞌睡"],
  },
  {
    emoji: "🤤",
    name: "drooling_face",
    category: "people",
    keywords: ["drool", "流口水"],
  },
  {
    emoji: "😴",
    name: "sleeping",
    category: "people",
    keywords: ["sleep", "zzz", "睡觉"],
  },
  {
    emoji: "😷",
    name: "mask",
    category: "people",
    keywords: ["sick", "口罩", "生病"],
  },
  {
    emoji: "🤒",
    name: "thermometer_face",
    category: "people",
    keywords: ["fever", "发烧", "生病"],
  },
  {
    emoji: "🤕",
    name: "head_bandage",
    category: "people",
    keywords: ["hurt", "头包扎", "受伤"],
  },
  {
    emoji: "🤢",
    name: "nauseated_face",
    category: "people",
    keywords: ["sick", "恶心", "呕吐"],
  },
  {
    emoji: "🤮",
    name: "vomiting_face",
    category: "people",
    keywords: ["puke", "吐了"],
  },
  {
    emoji: "🤧",
    name: "sneezing_face",
    category: "people",
    keywords: ["cold", "打喷嚏", "感冒"],
  },
  {
    emoji: "🥵",
    name: "hot_face",
    category: "people",
    keywords: ["heat", "热", "大汗"],
  },
  {
    emoji: "🥶",
    name: "cold_face",
    category: "people",
    keywords: ["freezing", "冷", "冻僵"],
  },
  {
    emoji: "🥴",
    name: "woozy_face",
    category: "people",
    keywords: ["drunk", "微醺", "眩晕"],
  },
  {
    emoji: "😵",
    name: "dizzy_face",
    category: "people",
    keywords: ["dead", "头晕"],
  },
  {
    emoji: "🤯",
    name: "exploding_head",
    category: "people",
    keywords: ["mindblown", "脑子炸了", "震惊"],
  },
  {
    emoji: "🤠",
    name: "cowboy_hat_face",
    category: "people",
    keywords: ["cowboy", "牛仔"],
  },
  {
    emoji: "🥳",
    name: "partying_face",
    category: "people",
    keywords: ["party", "celebrate", "庆祝", "聚会"],
  },
  {
    emoji: "😎",
    name: "sunglasses",
    category: "people",
    keywords: ["cool", "墨镜", "酷"],
  },
  {
    emoji: "🤓",
    name: "nerd",
    category: "people",
    keywords: ["geek", "书呆子", "极客"],
  },
  {
    emoji: "🧐",
    name: "monocle_face",
    category: "people",
    keywords: ["inspect", "单片眼镜", "观察"],
  },
  {
    emoji: "😕",
    name: "confused",
    category: "people",
    keywords: ["lost", "困惑"],
  },
  {
    emoji: "😟",
    name: "worried",
    category: "people",
    keywords: ["nervous", "担忧"],
  },
  {
    emoji: "😮",
    name: "open_mouth",
    category: "people",
    keywords: ["surprise", "张嘴"],
  },
  {
    emoji: "😯",
    name: "hushed",
    category: "people",
    keywords: ["quiet", "惊讶"],
  },
  {
    emoji: "😲",
    name: "astonished",
    category: "people",
    keywords: ["shocked", "大吃一惊"],
  },
  {
    emoji: "😳",
    name: "flushed",
    category: "people",
    keywords: ["shocked", "惊呆", "脸红"],
  },
  {
    emoji: "🥺",
    name: "pleading_face",
    category: "people",
    keywords: ["puppy", "可怜", "恳求", "委屈"],
  },
  {
    emoji: "😦",
    name: "frowning_face_with_open_mouth",
    category: "people",
    keywords: ["sad", "惊恐"],
  },
  {
    emoji: "😨",
    name: "fearful",
    category: "people",
    keywords: ["scared", "害怕"],
  },
  {
    emoji: "😰",
    name: "cold_sweat",
    category: "people",
    keywords: ["nervous", "焦虑", "冷汗"],
  },
  {
    emoji: "😥",
    name: "sad_but_relieved_face",
    category: "people",
    keywords: ["phew", "叹息"],
  },
  {
    emoji: "😢",
    name: "cry",
    category: "people",
    keywords: ["tear", "哭", "流泪"],
  },
  {
    emoji: "😭",
    name: "sob",
    category: "people",
    keywords: ["crying", "大哭", "痛哭"],
  },
  {
    emoji: "😱",
    name: "scream",
    category: "people",
    keywords: ["munch", "惊声尖叫", "吓死"],
  },
  {
    emoji: "😖",
    name: "confounded",
    category: "people",
    keywords: ["frustrated", "难耐"],
  },
  {
    emoji: "😣",
    name: "persevere",
    category: "people",
    keywords: ["struggle", "忍耐"],
  },
  {
    emoji: "😞",
    name: "disappointed",
    category: "people",
    keywords: ["sad", "失望"],
  },
  {
    emoji: "😓",
    name: "sweat",
    category: "people",
    keywords: ["stress", "汗颜"],
  },
  {
    emoji: "😩",
    name: "weary",
    category: "people",
    keywords: ["tired", "累瘫"],
  },
  {
    emoji: "😫",
    name: "tired_face",
    category: "people",
    keywords: ["exhausted", "心累"],
  },
  {
    emoji: "🥱",
    name: "yawning_face",
    category: "people",
    keywords: ["tired", "打哈欠"],
  },
  {
    emoji: "😤",
    name: "triumph",
    category: "people",
    keywords: ["angry", "傲娇", "哼"],
  },
  {
    emoji: "😡",
    name: "rage",
    category: "people",
    keywords: ["angry", "狂怒", "生气"],
  },
  { emoji: "😠", name: "angry", category: "people", keywords: ["mad", "愤怒"] },
  {
    emoji: "🤬",
    name: "cursing",
    category: "people",
    keywords: ["swear", "骂人", "嘴炮"],
  },
  {
    emoji: "😈",
    name: "smiling_imp",
    category: "people",
    keywords: ["devil", "小恶魔", "淘气"],
  },
  {
    emoji: "👿",
    name: "imp",
    category: "people",
    keywords: ["devil", "恶魔", "愤怒"],
  },
  {
    emoji: "💀",
    name: "skull",
    category: "people",
    keywords: ["dead", "头骨", "骷髅", "笑死"],
  },
  {
    emoji: "☠️",
    name: "skull_and_crossbones",
    category: "people",
    keywords: ["danger", "骷髅旗", "海盗"],
  },
  {
    emoji: "💩",
    name: "poop",
    category: "people",
    keywords: ["crap", "便便", "大便"],
  },
  {
    emoji: "🤡",
    name: "clown",
    category: "people",
    keywords: ["joker", "小丑"],
  },
  {
    emoji: "👻",
    name: "ghost",
    category: "people",
    keywords: ["spooky", "幽灵", "鬼魂"],
  },
  {
    emoji: "👽",
    name: "alien",
    category: "people",
    keywords: ["ufo", "外星人"],
  },
  {
    emoji: "👾",
    name: "space_invader",
    category: "people",
    keywords: ["game", "像素怪兽"],
  },
  {
    emoji: "🤖",
    name: "robot",
    category: "people",
    keywords: ["bot", "机器人"],
  },
  {
    emoji: "👋",
    name: "wave",
    category: "people",
    keywords: ["hand", "hello", "挥手", "再见"],
  },
  {
    emoji: "👍",
    name: "thumbsup",
    category: "people",
    keywords: ["like", "赞", "大拇指", "好"],
  },
  {
    emoji: "👎",
    name: "thumbsdown",
    category: "people",
    keywords: ["dislike", "差评", "踩"],
  },
  {
    emoji: "👊",
    name: "punch",
    category: "people",
    keywords: ["fist", "拳头"],
  },
  {
    emoji: "✌️",
    name: "peace",
    category: "people",
    keywords: ["victory", "剪刀手", "耶"],
  },
  {
    emoji: "👌",
    name: "ok_hand",
    category: "people",
    keywords: ["ok", "好的", "行"],
  },
  {
    emoji: "🤝",
    name: "handshake",
    category: "people",
    keywords: ["deal", "握手", "合作"],
  },
  {
    emoji: "👏",
    name: "clap",
    category: "people",
    keywords: ["applause", "鼓掌", "拍手"],
  },
  {
    emoji: "🙌",
    name: "raised_hands",
    category: "people",
    keywords: ["celebrate", "举双手", "欢呼"],
  },
  {
    emoji: "🙏",
    name: "pray",
    category: "people",
    keywords: ["please", "thank", "祈祷", "拜托", "谢谢"],
  },

  // Nature & Animals
  {
    emoji: "🐶",
    name: "dog",
    category: "nature",
    keywords: ["puppy", "小狗", "汪汪"],
  },
  {
    emoji: "🐱",
    name: "cat",
    category: "nature",
    keywords: ["kitty", "小猫", "喵"],
  },
  {
    emoji: "🐭",
    name: "mouse",
    category: "nature",
    keywords: ["rat", "小老鼠"],
  },
  {
    emoji: "🐹",
    name: "hamster",
    category: "nature",
    keywords: ["pet", "仓鼠"],
  },
  {
    emoji: "🐰",
    name: "rabbit",
    category: "nature",
    keywords: ["bunny", "兔子"],
  },
  {
    emoji: "🦊",
    name: "fox",
    category: "nature",
    keywords: ["animal", "狐狸"],
  },
  { emoji: "🐻", name: "bear", category: "nature", keywords: ["animal", "熊"] },
  {
    emoji: "🐼",
    name: "panda",
    category: "nature",
    keywords: ["bear", "大熊猫"],
  },
  {
    emoji: "🐨",
    name: "koala",
    category: "nature",
    keywords: ["animal", "考拉"],
  },
  {
    emoji: "🐯",
    name: "tiger",
    category: "nature",
    keywords: ["animal", "老虎"],
  },
  {
    emoji: "🦁",
    name: "lion",
    category: "nature",
    keywords: ["animal", "狮子"],
  },
  { emoji: "🐮", name: "cow", category: "nature", keywords: ["beef", "奶牛"] },
  { emoji: "🐷", name: "pig", category: "nature", keywords: ["pork", "小猪"] },
  { emoji: "🐸", name: "frog", category: "nature", keywords: ["toad", "青蛙"] },
  {
    emoji: "🐵",
    name: "monkey",
    category: "nature",
    keywords: ["ape", "猴子"],
  },
  {
    emoji: "🐔",
    name: "chicken",
    category: "nature",
    keywords: ["rooster", "小鸡"],
  },
  {
    emoji: "🐧",
    name: "penguin",
    category: "nature",
    keywords: ["bird", "企鹅"],
  },
  {
    emoji: "🐦",
    name: "bird",
    category: "nature",
    keywords: ["animal", "小鸟"],
  },
  { emoji: "🦆", name: "duck", category: "nature", keywords: ["bird", "鸭子"] },
  {
    emoji: "🦅",
    name: "eagle",
    category: "nature",
    keywords: ["bird", "老鹰"],
  },
  {
    emoji: "🦉",
    name: "owl",
    category: "nature",
    keywords: ["bird", "猫头鹰"],
  },
  {
    emoji: "🦇",
    name: "bat",
    category: "nature",
    keywords: ["animal", "蝙蝠"],
  },
  { emoji: "🐺", name: "wolf", category: "nature", keywords: ["animal", "狼"] },
  { emoji: "🐗", name: "boar", category: "nature", keywords: ["pig", "野猪"] },
  {
    emoji: "🐴",
    name: "horse",
    category: "nature",
    keywords: ["pony", "小马"],
  },
  {
    emoji: "🦄",
    name: "unicorn",
    category: "nature",
    keywords: ["magic", "独角兽"],
  },
  { emoji: "🐝", name: "bee", category: "nature", keywords: ["honey", "蜜蜂"] },
  {
    emoji: "🐛",
    name: "bug",
    category: "nature",
    keywords: ["insect", "毛毛虫"],
  },
  {
    emoji: "🦋",
    name: "butterfly",
    category: "nature",
    keywords: ["insect", "蝴蝶"],
  },
  {
    emoji: "🐌",
    name: "snail",
    category: "nature",
    keywords: ["slow", "蜗牛"],
  },
  {
    emoji: "🌲",
    name: "evergreen_tree",
    category: "nature",
    keywords: ["pine", "松树", "常青树"],
  },
  {
    emoji: "🌳",
    name: "deciduous_tree",
    category: "nature",
    keywords: ["nature", "大树"],
  },
  {
    emoji: "🌴",
    name: "palm_tree",
    category: "nature",
    keywords: ["beach", "棕榈树", "椰树"],
  },
  {
    emoji: "🌱",
    name: "seedling",
    category: "nature",
    keywords: ["plant", "幼苗", "发芽"],
  },
  {
    emoji: "🌿",
    name: "herb",
    category: "nature",
    keywords: ["green", "药草", "叶子"],
  },
  {
    emoji: "🍀",
    name: "four_leaf_clover",
    category: "nature",
    keywords: ["luck", "四叶草", "幸运"],
  },
  {
    emoji: "🍁",
    name: "maple_leaf",
    category: "nature",
    keywords: ["fall", "枫叶", "秋天"],
  },
  {
    emoji: "🌸",
    name: "cherry_blossom",
    category: "nature",
    keywords: ["flower", "樱花"],
  },
  {
    emoji: "🌹",
    name: "rose",
    category: "nature",
    keywords: ["flower", "玫瑰", "红花"],
  },
  {
    emoji: "🌻",
    name: "sunflower",
    category: "nature",
    keywords: ["flower", "向日葵"],
  },
  {
    emoji: "🌞",
    name: "sun_with_face",
    category: "nature",
    keywords: ["sunny", "太阳公公"],
  },
  {
    emoji: "⭐",
    name: "star",
    category: "nature",
    keywords: ["night", "星星"],
  },
  {
    emoji: "🌟",
    name: "glowing_star",
    category: "nature",
    keywords: ["sparkle", "闪烁的星"],
  },
  {
    emoji: "⚡",
    name: "zap",
    category: "nature",
    keywords: ["lightning", "闪电", "雷电"],
  },
  {
    emoji: "🔥",
    name: "fire",
    category: "nature",
    keywords: ["flame", "火", "热门"],
  },
  {
    emoji: "🌈",
    name: "rainbow",
    category: "nature",
    keywords: ["colors", "彩虹"],
  },

  // Food & Drink
  {
    emoji: "🍏",
    name: "green_apple",
    category: "food",
    keywords: ["fruit", "青苹果"],
  },
  {
    emoji: "🍎",
    name: "apple",
    category: "food",
    keywords: ["fruit", "红苹果"],
  },
  { emoji: "🍐", name: "pear", category: "food", keywords: ["fruit", "雪梨"] },
  {
    emoji: "🍊",
    name: "tangerine",
    category: "food",
    keywords: ["orange", "橘子", "橙子"],
  },
  { emoji: "🍋", name: "lemon", category: "food", keywords: ["sour", "柠檬"] },
  {
    emoji: "🍌",
    name: "banana",
    category: "food",
    keywords: ["fruit", "香蕉"],
  },
  {
    emoji: "🍉",
    name: "watermelon",
    category: "food",
    keywords: ["fruit", "西瓜"],
  },
  {
    emoji: "🍇",
    name: "grapes",
    category: "food",
    keywords: ["fruit", "葡萄"],
  },
  {
    emoji: "🍓",
    name: "strawberry",
    category: "food",
    keywords: ["fruit", "草莓"],
  },
  { emoji: "🍑", name: "peach", category: "food", keywords: ["fruit", "桃子"] },
  { emoji: "🥭", name: "mango", category: "food", keywords: ["fruit", "芒果"] },
  {
    emoji: "🍍",
    name: "pineapple",
    category: "food",
    keywords: ["fruit", "菠萝"],
  },
  {
    emoji: "🥥",
    name: "coconut",
    category: "food",
    keywords: ["fruit", "椰子"],
  },
  {
    emoji: "🥝",
    name: "kiwi_fruit",
    category: "food",
    keywords: ["fruit", "猕猴桃"],
  },
  {
    emoji: "🍅",
    name: "tomato",
    category: "food",
    keywords: ["vegetable", "西红柿"],
  },
  {
    emoji: "🥑",
    name: "avocado",
    category: "food",
    keywords: ["food", "牛油果"],
  },
  {
    emoji: "🍔",
    name: "hamburger",
    category: "food",
    keywords: ["fastfood", "汉堡"],
  },
  { emoji: "🍟", name: "fries", category: "food", keywords: ["chips", "薯条"] },
  { emoji: "🍕", name: "pizza", category: "food", keywords: ["pie", "披萨"] },
  {
    emoji: "🌭",
    name: "hotdog",
    category: "food",
    keywords: ["sausage", "热狗"],
  },
  {
    emoji: "🥪",
    name: "sandwich",
    category: "food",
    keywords: ["lunch", "三明治"],
  },
  {
    emoji: "🌮",
    name: "taco",
    category: "food",
    keywords: ["mexican", "塔可"],
  },
  {
    emoji: "🍜",
    name: "ramen",
    category: "food",
    keywords: ["noodles", "拉面", "面条"],
  },
  {
    emoji: "🍣",
    name: "sushi",
    category: "food",
    keywords: ["japanese", "寿司"],
  },
  {
    emoji: "🥟",
    name: "dumpling",
    category: "food",
    keywords: ["chinese", "饺子"],
  },
  {
    emoji: "🍦",
    name: "icecream",
    category: "food",
    keywords: ["dessert", "冰淇淋"],
  },
  {
    emoji: "🍰",
    name: "cake",
    category: "food",
    keywords: ["birthday", "蛋糕"],
  },
  { emoji: "☕", name: "coffee", category: "food", keywords: ["cafe", "咖啡"] },
  { emoji: "🍵", name: "tea", category: "food", keywords: ["green_tea", "茶"] },
  { emoji: "🍺", name: "beer", category: "food", keywords: ["drink", "啤酒"] },

  // Activities & Sports
  {
    emoji: "⚽",
    name: "soccer",
    category: "activities",
    keywords: ["football", "足球"],
  },
  {
    emoji: "🏀",
    name: "basketball",
    category: "activities",
    keywords: ["sports", "篮球"],
  },
  {
    emoji: "🏈",
    name: "football",
    category: "activities",
    keywords: ["sports", "橄榄球"],
  },
  {
    emoji: "⚾",
    name: "baseball",
    category: "activities",
    keywords: ["sports", "棒球"],
  },
  {
    emoji: "🎾",
    name: "tennis",
    category: "activities",
    keywords: ["sports", "网球"],
  },
  {
    emoji: "🏐",
    name: "volleyball",
    category: "activities",
    keywords: ["sports", "排球"],
  },
  {
    emoji: "🎱",
    name: "8ball",
    category: "activities",
    keywords: ["billiards", "台球", "黑八"],
  },
  {
    emoji: "🏓",
    name: "ping_pong",
    category: "activities",
    keywords: ["table_tennis", "乒乓球"],
  },
  {
    emoji: "🏸",
    name: "badminton",
    category: "activities",
    keywords: ["sports", "羽毛球"],
  },
  {
    emoji: "🥊",
    name: "boxing_glove",
    category: "activities",
    keywords: ["fight", "拳击"],
  },
  {
    emoji: "🎯",
    name: "dart",
    category: "activities",
    keywords: ["bullseye", "飞镖", "靶心"],
  },
  {
    emoji: "🎮",
    name: "video_game",
    category: "activities",
    keywords: ["console", "游戏机", "手柄"],
  },
  {
    emoji: "🎲",
    name: "game_die",
    category: "activities",
    keywords: ["dice", "骰子"],
  },
  {
    emoji: "🎨",
    name: "art",
    category: "activities",
    keywords: ["paint", "调色板", "画画"],
  },
  {
    emoji: "🎭",
    name: "performing_arts",
    category: "activities",
    keywords: ["drama", "面具", "话剧"],
  },
  {
    emoji: "🎤",
    name: "microphone",
    category: "activities",
    keywords: ["sing", "麦克风", "唱K"],
  },
  {
    emoji: "🎧",
    name: "headphones",
    category: "activities",
    keywords: ["music", "耳机", "音乐"],
  },

  // Travel & Places
  {
    emoji: "🚗",
    name: "car",
    category: "travel",
    keywords: ["automobile", "小轿车"],
  },
  {
    emoji: "🚕",
    name: "taxi",
    category: "travel",
    keywords: ["cab", "出租车"],
  },
  {
    emoji: "🚌",
    name: "bus",
    category: "travel",
    keywords: ["vehicle", "公交车"],
  },
  {
    emoji: "🏎️",
    name: "racing_car",
    category: "travel",
    keywords: ["f1", "赛车"],
  },
  {
    emoji: "🚓",
    name: "police_car",
    category: "travel",
    keywords: ["cops", "警车"],
  },
  {
    emoji: "🚑",
    name: "ambulance",
    category: "travel",
    keywords: ["hospital", "救护车"],
  },
  {
    emoji: "🚒",
    name: "fire_engine",
    category: "travel",
    keywords: ["fire", "消防车"],
  },
  {
    emoji: "🚲",
    name: "bike",
    category: "travel",
    keywords: ["bicycle", "自行车"],
  },
  {
    emoji: "🛵",
    name: "motor_scooter",
    category: "travel",
    keywords: ["vespa", "小电驴", "踏板车"],
  },
  {
    emoji: "🏍️",
    name: "motorcycle",
    category: "travel",
    keywords: ["bike", "摩托车"],
  },
  {
    emoji: "✈️",
    name: "airplane",
    category: "travel",
    keywords: ["flight", "飞机"],
  },
  {
    emoji: "🚀",
    name: "rocket",
    category: "travel",
    keywords: ["space", "火箭", "起飞"],
  },
  {
    emoji: "🛸",
    name: "flying_saucer",
    category: "travel",
    keywords: ["ufo", "飞碟"],
  },
  {
    emoji: "⛵",
    name: "sailboat",
    category: "travel",
    keywords: ["boat", "帆船"],
  },
  {
    emoji: "🚢",
    name: "ship",
    category: "travel",
    keywords: ["boat", "轮船", "邮轮"],
  },
  {
    emoji: "🏠",
    name: "house",
    category: "travel",
    keywords: ["home", "房屋", "家"],
  },
  {
    emoji: "🏰",
    name: "castle",
    category: "travel",
    keywords: ["palace", "城堡"],
  },
  {
    emoji: "🗼",
    name: "tokyo_tower",
    category: "travel",
    keywords: ["japan", "铁塔"],
  },
  {
    emoji: "🗽",
    name: "statue_of_liberty",
    category: "travel",
    keywords: ["usa", "自由女神像"],
  },

  // Objects & Tools
  {
    emoji: "💡",
    name: "bulb",
    category: "objects",
    keywords: ["idea", "灯泡", "灵感"],
  },
  {
    emoji: "💻",
    name: "laptop",
    category: "objects",
    keywords: ["computer", "笔记本电脑"],
  },
  {
    emoji: "📱",
    name: "iphone",
    category: "objects",
    keywords: ["mobile", "手机"],
  },
  {
    emoji: "⌨️",
    name: "keyboard",
    category: "objects",
    keywords: ["type", "键盘"],
  },
  {
    emoji: "🖱️",
    name: "computer_mouse",
    category: "objects",
    keywords: ["mouse", "鼠标"],
  },
  {
    emoji: "💾",
    name: "floppy_disk",
    category: "objects",
    keywords: ["save", "磁盘", "软盘"],
  },
  {
    emoji: "💿",
    name: "cd",
    category: "objects",
    keywords: ["optical", "光盘"],
  },
  {
    emoji: "📷",
    name: "camera",
    category: "objects",
    keywords: ["photo", "相机"],
  },
  {
    emoji: "🎥",
    name: "movie_camera",
    category: "objects",
    keywords: ["film", "摄影机"],
  },
  {
    emoji: "📺",
    name: "tv",
    category: "objects",
    keywords: ["television", "电视机"],
  },
  {
    emoji: "🔔",
    name: "bell",
    category: "objects",
    keywords: ["ring", "铃铛", "通知"],
  },
  {
    emoji: "📦",
    name: "package",
    category: "objects",
    keywords: ["box", "包裹", "快递"],
  },
  {
    emoji: "🎁",
    name: "gift",
    category: "objects",
    keywords: ["present", "礼物"],
  },
  {
    emoji: "🎉",
    name: "tada",
    category: "objects",
    keywords: ["party", "拉花", "庆祝", "礼炮"],
  },
  {
    emoji: "🎈",
    name: "balloon",
    category: "objects",
    keywords: ["party", "气球"],
  },
  { emoji: "🔑", name: "key", category: "objects", keywords: ["lock", "钥匙"] },
  {
    emoji: "🔒",
    name: "lock",
    category: "objects",
    keywords: ["secure", "锁住"],
  },
  {
    emoji: "🔓",
    name: "unlock",
    category: "objects",
    keywords: ["open", "开锁"],
  },

  // Symbols & Shapes
  {
    emoji: "❤️",
    name: "red_heart",
    category: "symbols",
    keywords: ["love", "红心", "爱心"],
  },
  {
    emoji: "🧡",
    name: "orange_heart",
    category: "symbols",
    keywords: ["love", "橙心"],
  },
  {
    emoji: "💛",
    name: "yellow_heart",
    category: "symbols",
    keywords: ["love", "黄心"],
  },
  {
    emoji: "💚",
    name: "green_heart",
    category: "symbols",
    keywords: ["love", "绿心"],
  },
  {
    emoji: "💙",
    name: "blue_heart",
    category: "symbols",
    keywords: ["love", "蓝心"],
  },
  {
    emoji: "💜",
    name: "purple_heart",
    category: "symbols",
    keywords: ["love", "紫心"],
  },
  {
    emoji: "🖤",
    name: "black_heart",
    category: "symbols",
    keywords: ["love", "黑心"],
  },
  {
    emoji: "🤍",
    name: "white_heart",
    category: "symbols",
    keywords: ["love", "白心"],
  },
  {
    emoji: "💔",
    name: "broken_heart",
    category: "symbols",
    keywords: ["sad", "心碎"],
  },
  {
    emoji: "💖",
    name: "sparkling_heart",
    category: "symbols",
    keywords: ["love", "闪亮的心"],
  },
  {
    emoji: "✨",
    name: "sparkles",
    category: "symbols",
    keywords: ["magic", "星星", "闪光"],
  },
  {
    emoji: "💯",
    name: "100",
    category: "symbols",
    keywords: ["score", "满分", "一百分"],
  },
  {
    emoji: "✅",
    name: "white_check_mark",
    category: "symbols",
    keywords: ["ok", "勾", "对勾"],
  },
  {
    emoji: "❌",
    name: "x",
    category: "symbols",
    keywords: ["no", "叉", "错误"],
  },
  {
    emoji: "⚠️",
    name: "warning",
    category: "symbols",
    keywords: ["alert", "警告"],
  },
  {
    emoji: "⛔",
    name: "no_entry",
    category: "symbols",
    keywords: ["stop", "禁止进入"],
  },
  {
    emoji: "🚫",
    name: "prohibited",
    category: "symbols",
    keywords: ["stop", "禁止"],
  },

  // Flags
  {
    emoji: "🏁",
    name: "checkered_flag",
    category: "flags",
    keywords: ["racing", "终点旗"],
  },
  {
    emoji: "🚩",
    name: "triangular_flag_on_post",
    category: "flags",
    keywords: ["red_flag", "红旗"],
  },
  {
    emoji: "🏳️",
    name: "white_flag",
    category: "flags",
    keywords: ["peace", "白旗"],
  },
  {
    emoji: "🏴",
    name: "black_flag",
    category: "flags",
    keywords: ["pirate", "黑旗"],
  },
  {
    emoji: "🇨🇳",
    name: "flag_cn",
    category: "flags",
    keywords: ["china", "中国国旗"],
  },
  {
    emoji: "🇺🇸",
    name: "flag_us",
    category: "flags",
    keywords: ["usa", "美国国旗"],
  },
  {
    emoji: "🇯🇵",
    name: "flag_jp",
    category: "flags",
    keywords: ["japan", "日本国旗"],
  },
  {
    emoji: "🇬🇧",
    name: "flag_gb",
    category: "flags",
    keywords: ["uk", "英国国旗"],
  },
];
